# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74526836b130b025c28dac67ee8bee984a19520eb98aae868fdf830b610f66f4aa8a955e7d1d7c64df2cd05eb3e82980ee25c51592dc8a6ac7b6c4a8b4081296

test:
  secret_key_base: 57bc88e409c0c5574f369b7cf6b12d69ea91af18ff725782e1eeabd435a4ad39257878bc6cdd42e6b6fa4ceafa7e138f485c9c9952c1516541cf417540e187fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
